=== nakasyou/lmspecs/schema/meta-models.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Official name.",
      "examples": ["GPT-4o", "Gemini 2.0 Flash"]
    },
    "id": {
      "type": "string",
      "description": "Official ID",
      "examples": ["gemini-2.0-flash"]
    },
    "creator": {
      "type": "array",
      "description": "Creator of the model.",
      "items": {
        "type": "string",
        "enum": [
          "GOOGLE",
          "xAI",
          "OpenAI",
          "DeepSeek"
        ]
      }
    },
    "published": {
      "type": "string",
      "pattern": "[0-9]{4}-[0-9]{2}-[0-9]{2}"
    },
    "states": {
      "type": "object",
      "patternProperties": {
        "[0-9]{4}-[0-9]{2}-[0-9]{2}": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "STABLE",
              "DEPRECATED",
              "EXPERIMENTAL"
            ]
          }
        }
      },
      "additionalProperties": false
    },
    "prev": {
      "type": "string",
      "description": "Prev version ID"
    },
    "lmarena_id": {
      "type": "string"
    },
    "cutoff_date": {
      "type": "object",
      "properties": {
        "value": {
          "type": "string",
          "pattern": "^[0-9]{4}-[0-9]{2}(-[0-9]{2})?$"
        },
        "sources": { "type": "array", "items": { "type": "string" } }
      }
    },
    "tokens_limit": {
      "type": "object",
      "properties": {
        "input": { "type": "number" },
        "output": { "type": "number" },
        "sources": { "type": "array", "items": { "type": "string" } }
      }
    },
    "license": {
      "type": "object",
      "properties": {
        "value": {
          "type": "string",
          "enum": ["Proprietary", "MIT"]
        }
      }
    }
  }
}

=== nakasyou/lmspecs/models/gemini-2.0-flash-lite-001/meta.json
{
  "$schema": "../../schema/meta-models.json",
  "id": "gemini-2.0-flash-lite-001",
  "name": "Gemini 2.0 Flash Lite 001",
  "creator": ["GOOGLE"],
  "published": "2025-02-25",
  "states": {
    "2024-02-25": ["STABLE"]
  },
  "cutoff_date": {
    "value": "2024-06",
    "sources": [
      "https://firebase.google.com/docs/vertex-ai/models#specs-and-limitations-comparison"
    ]
  },
  "tokens_limit": {
    "input": 1048576,
    "output": 8192
  }
}

=== nakasyou/lmspecs/models/o1-pro-2025-03-19/meta.json
{
  "$schema": "../../schema/meta-models.json",
  "id": "o1-pro-2025-03-19",
  "name": "o1-pro (2025-03-19)",
  "creator": ["OpenAI"],
  "published": "2025-03-19",
  "states": {
    "2025-03-19": ["STABLE"]
  },
  "cutoff_date": {
    "value": "2023-10"
  },
  "tokens_limit": {
    "input": 200000,
    "output": 100000
  }
}

=== nakasyou/lmspecs/models/gpt-4o-2024-11-20/meta.json
{
  "$schema": "../../schema/meta-models.json",
  "id": "gpt-4o-2024-11-20",
  "name": "GPT-4o (2024-11-20)",
  "creator": ["OpenAI"],
  "published": "2024-11-20",
  "states": {
    "2024-11-20": ["STABLE"]
  },
  "lmarena_id": "chatgpt-4o-latest-20241120",
  "cutoff_date": {
    "value": "2023-10"
  },
  "tokens_limit": {
    "input": 128000,
    "output": 16384
  }
}
