=== nakasyou/lmspecs/schema/_output/models/meta.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "creators": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "const": "Google"
          },
          {
            "const": "xAI"
          },
          {
            "const": "OpenAI"
          },
          {
            "const": "DeepSeek"
          },
          {
            "const": "Anthropic"
          },
          {
            "const": "Cohere"
          },
          {
            "const": "CohereForAI"
          }
        ]
      }
    },
    "published_at": {
      "type": "object",
      "properties": {
        "value": {
          "type": "string",
          "pattern": "[0-9]{4}-[0-9]{2}-[0-9]{2}"
        },
        "references": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "url": {
                "type": "string"
              },
              "retrieved": {
                "type": "string"
              }
            },
            "required": [
              "url",
              "retrieved"
            ]
          }
        }
      },
      "required": [
        "value",
        "references"
      ]
    },
    "states": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "anyOf": [
            {
              "const": "STABLE"
            },
            {
              "const": "DEPRECATED"
            },
            {
              "const": "EXPERIMENTAL"
            }
          ]
        }
      }
    },
    "prev": {
      "type": "string"
    },
    "identifiers": {
      "type": "object",
      "properties": {
        "lmarena": {
          "type": "string"
        }
      },
      "required": []
    },
    "cutoff_date": {
      "type": "object",
      "properties": {
        "value": {
          "type": "string",
          "pattern": "^[0-9]{4}-[0-9]{2}(-[0-9]{2})?$"
        },
        "references": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "url": {
                "type": "string"
              },
              "retrieved": {
                "type": "string"
              }
            },
            "required": [
              "url",
              "retrieved"
            ]
          }
        }
      },
      "required": [
        "value",
        "references"
      ]
    },
    "token_limit": {
      "type": "object",
      "properties": {
        "input": {
          "type": "number"
        },
        "output": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ]
        },
        "references": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "url": {
                "type": "string"
              },
              "retrieved": {
                "type": "string"
              }
            },
            "required": [
              "url",
              "retrieved"
            ]
          }
        }
      },
      "required": [
        "input",
        "output",
        "references"
      ]
    },
    "license": {
      "type": "object",
      "properties": {
        "value": {
          "anyOf": [
            {
              "const": "Proprietary"
            },
            {
              "const": "MIT"
            },
            {
              "const": "CC-BY-NC-4.0"
            },
            {
              "const": "Apache-2.0"
            }
          ]
        },
        "references": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "url": {
                "type": "string"
              },
              "retrieved": {
                "type": "string"
              }
            },
            "required": [
              "url",
              "retrieved"
            ]
          }
        }
      },
      "required": [
        "value",
        "references"
      ]
    },
    "links": {
      "type": "object",
      "properties": {
        "website": {
          "type": "string"
        },
        "github": {
          "type": "string"
        },
        "huggingface": {
          "type": "string"
        }
      },
      "required": []
    },
    "logos": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "multimodalities": {
      "type": "object",
      "properties": {
        "input": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "const": "image"
              },
              {
                "const": "text"
              },
              {
                "const": "audio"
              },
              {
                "const": "video"
              }
            ]
          }
        },
        "output": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "const": "text"
              },
              {
                "const": "image"
              },
              {
                "const": "audio"
              },
              {
                "const": "video"
              }
            ]
          }
        },
        "references": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "url": {
                "type": "string"
              },
              "retrieved": {
                "type": "string"
              }
            },
            "required": [
              "url",
              "retrieved"
            ]
          }
        }
      },
      "required": [
        "input",
        "output",
        "references"
      ]
    },
    "model_parameters": {
      "type": "object",
      "properties": {
        "value": {
          "type": "number"
        },
        "references": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "url": {
                "type": "string"
              },
              "retrieved": {
                "type": "string"
              }
            },
            "required": [
              "url",
              "retrieved"
            ]
          }
        },
        "trustability": {
          "anyOf": [
            {
              "const": "OFFICIAL"
            },
            {
              "const": "GUESSED"
            }
          ]
        }
      },
      "required": [
        "value",
        "references",
        "trustability"
      ]
    },
    "features": {
      "type": "object",
      "properties": {
        "value": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "const": "REASONING"
              },
              {
                "const": "FUNCTION_CALLING"
              }
            ]
          }
        },
        "references": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "url": {
                "type": "string"
              },
              "retrieved": {
                "type": "string"
              }
            },
            "required": [
              "url",
              "retrieved"
            ]
          }
        }
      },
      "required": [
        "value",
        "references"
      ]
    }
  },
  "required": [
    "$schema",
    "name",
    "id",
    "creators",
    "published_at",
    "states",
    "identifiers",
    "license",
    "multimodalities",
    "features"
  ]
}

=== nakasyou/lmspecs/models/o1-preview/meta.json
{
  "$schema": "../../schema/_output/models/meta.json",
  "id": "o1-preview",
  "name": "o1 preview",
  "creators": [
    "OpenAI"
  ],
  "published_at": {
    "value": "2024-09-12",
    "references": []
  },
  "states": {
    "2024-09-12": [
      "EXPERIMENTAL"
    ]
  },
  "cutoff_date": {
    "value": "2023-10",
    "references": []
  },
  "token_limit": {
    "input": 128000,
    "output": 32768,
    "references": []
  },
  "identifiers": {
    "lmarena": "o1-preview"
  },
  "license": {
    "value": "Proprietary",
    "references": []
  },
  "multimodalities": {
    "input": [
      "text"
    ],
    "output": [
      "text"
    ],
    "references": []
  },
  "features": {
    "value": [],
    "references": []
  }
}

=== nakasyou/lmspecs/models/grok-3/meta.json
{
  "$schema": "../../schema/_output/models/meta.json",
  "id": "grok-3",
  "name": "Grok 3",
  "creators": [
    "xAI"
  ],
  "published_at": {
    "value": "2025-02-17",
    "references": []
  },
  "states": {
    "2025-02-17": [
      "EXPERIMENTAL"
    ]
  },
  "cutoff_date": {
    "value": "2024-10-31",
    "references": [
      {
        "url": "https://www.reddit.com/r/grok/comments/1iubkvu/grok_3s_actual_knowledge_cutoff_date_is_october/",
        "retrieved": "2025-03-27T06:46:32.098Z"
      }
    ]
  },
  "token_limit": {
    "input": 1000000,
    "output": null,
    "references": [
      {
        "url": "https://x.ai/news/grok-3",
        "retrieved": "2025-03-27T06:55:32.158Z"
      }
    ]
  },
  "identifiers": {
    "lmarena": "early-grok-3"
  },
  "logos": [
    "grok-icon-2025/image.svg"
  ],
  "license": {
    "value": "Proprietary",
    "references": []
  },
  "multimodalities": {
    "input": [
      "text"
    ],
    "output": [
      "text"
    ],
    "references": []
  },
  "features": {
    "value": [
      "REASONING"
    ],
    "references": []
  }
}

=== nakasyou/lmspecs/models/gemini-1.5-flash-8b-001/meta.json
{
  "$schema": "../../schema/_output/models/meta.json",
  "id": "gemini-1.5-flash-8b-001",
  "name": "gemini-1.5-flash-8b-001",
  "creators": [
    "Google"
  ],
  "published_at": {
    "value": "2024-10-23",
    "references": []
  },
  "states": {
    "2024-10-23": [
      "STABLE"
    ]
  },
  "identifiers": {
    "lmarena": "gemini-1.5-flash-8b-001"
  },
  "logos": [
    "google-gemini-icon/image.svg"
  ],
  "token_limit": {
    "input": 1048576,
    "output": 8192,
    "references": []
  },
  "multimodalities": {
    "input": [
      "text",
      "image",
      "audio",
      "video"
    ],
    "output": [
      "text"
    ],
    "references": []
  },
  "license": {
    "value": "Proprietary",
    "references": []
  },
  "cutoff_date": {
    "value": "2024-10",
    "references": []
  },
  "features": {
    "value": ["FUNCTION_CALLING"],
    "references": []
  },
  "model_parameters": {
    "value": 80000000000,
    "trustability": "GUESSED",
    "references": []
  }
}

=== nakasyou/lmspecs/models/gpt-4-0613/meta.json
{
  "$schema": "../../schema/_output/models/meta.json",
  "id": "gpt-4-0613",
  "name": "GPT-4 0613",
  "creators": [
    "OpenAI"
  ],
  "published_at": {
    "value": "2023-06-13",
    "references": []
  },
  "states": {
    "2023-06-13": [
      "STABLE"
    ]
  },
  "cutoff_date": {
    "value": "2023-12-01",
    "references": [
      {
        "url": "https://platform.openai.com/docs/models/gpt-4",
        "retrieved": "2025-03-27T06:46:32.062Z"
      }
    ]
  },
  "token_limit": {
    "input": 8192,
    "output": 8192,
    "references": []
  },
  "identifiers": {
    "lmarena": "gpt-4-0613"
  },
  "license": {
    "value": "Proprietary",
    "references": []
  },
  "multimodalities": {
    "input": [
      "text"
    ],
    "output": [
      "text"
    ],
    "references": []
  },
  "features": {
    "value": [],
    "references": []
  }
}

=== nakasyou/lmspecs/models/deepseek-r1/meta.json
{
  "$schema": "../../schema/_output/models/meta.json",
  "id": "deepseek-r1",
  "name": "DeepSeek R1",
  "creators": [
    "DeepSeek"
  ],
  "published_at": {
    "value": "2025-01-20",
    "references": []
  },
  "states": {
    "2025-01-20": [
      "STABLE"
    ]
  },
  "identifiers": {
    "lmarena": "deepseek-r1"
  },
  "logos": ["deepseek-icon/image.svg"],
  "license": {
    "value": "MIT",
    "references": []
  },
  "links": {
    "huggingface": "https://huggingface.co/deepseek-ai/DeepSeek-R1"
  },
  "multimodalities": {
    "input": [
      "text"
    ],
    "output": [
      "text"
    ],
    "references": []
  },
  "cutoff_date": {
    "value": "2024-10",
    "references": []
  },
  "token_limit": {
    "input": 128000,
    "output": null,
    "references": []
  },
  "features": {
    "value": ["REASONING"],
    "references": []
  }
}

=== nakasyou/lmspecs/models/claude-3-opus-20240229/meta.json
{
  "$schema": "../../schema/_output/models/meta.json",
  "id": "claude-3-opus-20240229",
  "name": "claude-3-opus-20240229",
  "creators": [
    "Anthropic"
  ],
  "published_at": {
    "value": "2024-02-29",
    "references": []
  },
  "states": {
    "2024-02-29": [
      "STABLE"
    ]
  },
  "identifiers": {
    "lmarena": "claude-3-opus-20240229"
  },
  "license": {
    "value": "Proprietary",
    "references": []
  },
  "multimodalities": {
    "input": [
      "text",
      "image"
    ],
    "output": [
      "text"
    ],
    "references": []
  },
  "cutoff_date": {
    "value": "2023-08",
    "references": []
  },
  "token_limit": {
    "input": 200000,
    "output": 4096,
    "references": []
  },
  "features": {
    "value": [],
    "references": []
  }
}
